### ISSUE TITLE
Donut-Maven-Plugin is not supporting Cucumber-Junit latest version

### ISSUE THREAD

**Issue by ksanthanu12** [MagenTys/donut-maven-plugin#14]
Donut-Maven-Plugin is not supporting Cucumber-Junit latest version. 
Latest cucumber Junit version is 4.2.0.
Also donut should support the 'Rerun Failing Tests' capability which is introduced in the latest version of Junit.

**Comment by davebassan** [comment]
donut-maven-plugin now supports the latest cucumber JSON output format for cucumber 4.2
